### ISSUE TITLE
Include the problem in the file

### ISSUE THREAD

**Issue by omertairi04** [ArbUseini/Program-Solutions#1]
I think including the problem gives more insight on what problem the code solves.

**Comment by ArbUseini** [comment]
That I definitely agree with. We need to do that (any suggestions?) on how
to do it?

**Comment by omertairi04** [comment]
I've worked on some files which i think is good. Ill push changes soon.

**Comment by ArbUseini** [comment]
thanks man!

**Comment by DardanMehmedi** [comment]
I've added the problems to all of the code in [Exercises (for the first partial exam)
