### ISSUE TITLE
Don't include problem in code

### ISSUE THREAD

**Issue by ArbUseini** [ArbUseini/Program-Solutions#18]
I think it's a bit counterintuitive to add the problem in the code since the reason people check out the repo is that they can't solve a certain problem, that they already read, so they already know what the problem says, and also we can use the time that is freed from that to explaining something complex about our code that chat gpt maybe might not be able to decipher properly. (this will happen about 5% of the time so that means less work for us) If you (don't) agree please comment so we know how to move forward with our solutions.

**Comment by omertairi04** [comment]
Should i remove the problems from already existing files?

**Comment by ArbUseini** [comment]
Moving them to the end of the file would be a good move, or just adding a .txt file with the questions. Either would work

**Comment by omertairi04** [comment]
We've decided to not include the code in the file!
